### PR TITLE
Remove image pull secret

### PR DESCRIPTION
**Pull request by fiunchinho**
The image is public, we don't need this.

### CODE REVIEW

**Comment by tfussell** [comment]
You can probably remove this as well https://github.com/giantswarm/node-operator/blob/master/helm/node-operator-chart/values.yaml#L25-L26

**Comment by xh3b4sd** [comment]
Are we sure it will stay public? We often think about private registry use especially for environments like China where installations have limitations and may be different. I would like to make a conscious decision here and not simply throw something away that may be useful later. Not blocking here. Just some food for thought.

**Comment by rossf7** [comment]
> Are we sure it will stay public? We often think about private registry for environments like China

Yes good point. We want a local registry for caching but it would probably have to be private.

Maybe we can make a decision in sig-releng? It's a trade off as removing this simplifies our charts and integration tests.

**Comment by MarcelMue** [comment]
Please rebuild the workflow to get a green build.

I am fine with this - I personally think having a pull secret when the image is public is not necessary. Let's introduce the secret when we need it.

**Comment by fiunchinho** [comment]
Done. I just need approvals :smile: . If I understand correctly, the decision is to add the secret when needed

**Pull request merged**
